In [1]:
## importing models
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB 
from sklearn.svm import SVC

from sklearn.ensemble import VotingClassifier

import pandas as  pd

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv(r"C:\Users\Skuad\Downloads\heart.csv")

In [3]:
df.shape

(303, 14)

In [4]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
## input Variables = x
## output variables = y 

y=df['target']

x=df.drop('target',axis=1)
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [7]:
## test and Train Split

X_train,X_test,y_train, y_test = train_test_split( x,y,test_size=.25,random_state=50)

In [8]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()
nbg_clf = GaussianNB()

In [9]:
for clf in (log_clf, nbg_clf, rnd_clf, svm_clf):
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.8026315789473685
GaussianNB 0.7631578947368421
RandomForestClassifier 0.8289473684210527
SVC 0.6578947368421053

In [10]:
voting_clf = VotingClassifier(estimators=[('lr', log_clf),('nb',nbg_clf), ('rf', rnd_clf), ('svc', svm_clf)])

for clf in (log_clf, nbg_clf, rnd_clf, svm_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.8026315789473685
GaussianNB 0.7631578947368421
RandomForestClassifier 0.8421052631578947
SVC 0.6578947368421053
VotingClassifier 0.7763157894736842

In [11]:
log_clf = LogisticRegression()
#rnd_clf = RandomForestClassifie()
svm_clf = SVC()
voting_clf = VotingClassifier( estimators=[('lr', log_clf), ('svc', svm_clf)], voting='hard')
voting_clf.fit(X_train, y_train)
from sklearn.metrics import accuracy_score
for clf in (log_clf,svm_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

LogisticRegression 0.8026315789473685
SVC 0.6578947368421053
VotingClassifier 0.7236842105263158

In [12]:
X_train,X_test,y_train, y_test = train_test_split( x,y,test_size=.25,random_state =130)
rnd_clf = RandomForestClassifier()
svm_clf = SVC()
nb =GaussianNB()
voting_clf = VotingClassifier(estimators=[('rf', rnd_clf),('nbg', nb),  ('svc', svm_clf)], voting='hard')


for clf in ( rnd_clf, svm_clf, nb,voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

RandomForestClassifier 0.7631578947368421
SVC 0.6447368421052632
GaussianNB 0.75
VotingClassifier 0.7368421052631579